version: '3.3'
services:
  online-library-catalog:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: konradmaciejczyk/online-library-catalog
    container_name: online-library-catalog
    command: python manage.py runserver 0.0.0.0:8000